---
  name: Go Security Check
  on:
    push:
      branches:
        - main
      paths:
        - '**.go'
        - 'vendor/**'
        - '.github/workflows/**'
      
    pull_request:
      types: ['opened', 'synchronize']
      paths:
        - '**.go'
        - 'vendor/**'
        - '.github/workflows/**'

    schedule:
      - cron: '0 0 * * 0'
  
  jobs:
    gosec:
       name: gosec
       runs-on: ubuntu-latest
       steps:
         - name: Checkout Source
           uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
         - name: Run Gosec Security Scanner
           uses: securego/gosec@be8bd6e40be105333f2bc783ba8d688154441559 # v2.21.3
           with:
             args: '-no-fail -fmt sarif -out results.sarif ./...'
         - name: Upload SARIF file
           uses: github/codeql-action/upload-sarif@8f1a6fed33af5212fab8a999d004627ae8901d1b # v2.17.5
           with:
             sarif_file: results.sarif