---
name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

jobs:
  golangci:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: "v1.59"
          args: -v
