---
name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

jobs:
  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 # v6.0.1
        with:
          version: "v1.59"
          args: -v
