---
name: Lint
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - "vendor/**"
      - ".github/workflows/**"

jobs:
  golangci:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true
      - uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: "v1.59"
          args: -v
